root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
include_dir = ["app", "core", "docs", "middleware", "models", "routes", "storage", "templates", "translations", "vendor"]
exclude_file = []
delay = 100
stop_on_error = true
log = "logs/air.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
