basePath: /api
definitions:
  file.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  file.UploadResult:
    properties:
      filename:
        type: string
      path:
        type: string
      size:
        type: integer
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  oauth.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  users.User:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  websocket.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: This is the API documentation for Albafone
  title: Base API
  version: "1.5"
paths:
  /oauth/facebook/callback:
    post:
      consumes:
      - application/json
      description: Handle the OAuth callback from Facebook
      parameters:
      - description: Facebook Access Token
        in: body
        name: accessToken
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/oauth.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/oauth.ErrorResponse'
      summary: Facebook OAuth callback
      tags:
      - OAuth
  /oauth/google/callback:
    post:
      consumes:
      - application/json
      description: Handle the OAuth callback from Google
      parameters:
      - description: Google ID Token
        in: body
        name: idToken
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/oauth.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/oauth.ErrorResponse'
      summary: Google OAuth callback
      tags:
      - OAuth
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/file.UploadResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/file.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload a file
      tags:
      - Core/FileUpload
  /ws:
    get:
      consumes:
      - application/json
      description: Establishes a WebSocket connection
      parameters:
      - description: Client ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/websocket.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Connect to WebSocket
      tags:
      - Core/Websocket
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Api-Key
    type: apiKey
swagger: "2.0"
